### ISSUE TITLE
"modal' position

### ISSUE THREAD

**Issue by ClubACNews** [brianteeman/loginmodal#11]
Hi,
I'm interest by this module but i find not in the listing the "modal' position
-> Enable the plugin and publish the login module in a position called modal.

Thanks

I use the template "Cassiopeia"
François

**Comment by brianteeman** [comment]
You have to create the position

**Comment by ClubACNews** [comment]
Hi, it's ok now but by no means clear for a beginner.
I had to look up how to do it on another site to add a new position to a template.
I will try to add other features like "create an account".
THANKS
Francois
