### ISSUE TITLE
Modal Login is not working on some pages - How to solve this?

### ISSUE THREAD

**Issue by XenyFord** [brianteeman/loginmodal#12]
Mr. Teenman, Good morning :)

I hope you are doing great, sir!

I've enabled the Modal Login module on a website, and it is working fine on all the pages except a page where the EventBooking component is enabled. It has just disappeared from creating a popup div. I request you to please be so kind to help me rectify this problem.

Website: https://astro-remedies.com/events

Thank you in advance for your help!

![ERROR](https://github.com/joomla/joomla-cms/assets/89290310/80fdb765-3d54-4159-bac7-347dd51cd4c9)

---Working Modal on other pages ---

![WORKING POPUP](https://github.com/joomla/joomla-cms/assets/89290310/0fca5088-5d79-4841-a48e-810f8c8a1a0f)

**Comment by brianteeman** [comment]
There is a conflict with the javascript being used by the events component. Sorry nothing I can do about that
