### ISSUE TITLE
Append modal HTML to end of body

### ISSUE THREAD

**Issue by jendrage** [brianteeman/loginmodal#14]
Hi Brian,

Thanks for making this! I had issues with the modal not working properly with some components, due to the positon within the html that the modal was rendering.

I've added a couple of lines to the js within the DOMConentLoaded event listener to get the modal html and move it to the very end of the body, which has solved my issues:

```
var modal = document.getElementById("loginModal");
document.body.appendChild(modal);

```
There is probably a better way to do this by inserting the html at the end of the body via the plugin event.
Jen

**Comment by jendrage** [comment]
In addition, I found that on some of my pages the modal HTML was present twice on the page, causing the modal not to work correctly, so I have used this JS to remove any duplicate modals and append one to end of body, which has fixed all issues for me now:

```
$script	= <<<SCRIPT
document.addEventListener("DOMContentLoaded", function() {
var login = document.querySelectorAll('$selector').forEach((login, index) => {login.setAttribute('data-bs-toggle', 'modal');login.setAttribute('data-bs-target', '#loginModal');});
var loginModals = document.querySelectorAll("#loginModal");
if (loginModals.length > 1) { for (var i = 1; i < loginModals.length; i++) { loginModals[i].parentNode.removeChild(loginModals[i]);}}
document.body.appendChild(loginModals[0]);
});
SCRIPT;
```

**Comment by brianteeman** [comment]
very weird but happy you solved it
