### ISSUE TITLE
What is the code to build the link to the Popup?

### ISSUE THREAD

**Issue by Chacapamac** [brianteeman/loginmodal#15]
• The plugin “[System - Login Modal] is **ON**
• I create the login module in the position “modal” and enabled it
The module is set to all languages /all pages

I try to put the link code in a module (with “Prepare Content”) that I use to show the login and language tool
I try —> a[href*="login"]
and —> a[href*="logout"]

**The code appear in plain text (not a link) ?????**

![Screen Shot 2024-03-27 at 6 55 31 PM](https://github.com/brianteeman/loginmodal/assets/1907276/0379e307-1301-446e-a04d-b90cb38628ac)

**You can also see the “User” icon that I use normally as the login link.**

**Good Day Brian!** 😃

**Comment by brianteeman** [comment]
You dont make any changes to any module

The only thing you **may** have to do is to change the Selector of the element that will be used to open the modal in the **plugin**

**Comment by Chacapamac** [comment]
**Thank You Brian.**

**My link element is** 
`<span class="brianlogin awesome"><i class="fas fa-user fa-fw fa-login"></i></span>`

**What should I enter in the plugin?**

**Comment by brianteeman** [comment]
.brianlogin
or
.fa-login

**Comment by Chacapamac** [comment]
**Thanks Brian, it work.** 😃
![Screen Shot 2024-04-01 at 9 45 51 AM](https://github.com/brianteeman/loginmodal/assets/1907276/b820fc7c-877e-4651-86de-61ce4a198f1d)


**One thing the link is not actually an ahref link in the html code?**

![Screen Shot 2024-04-01 at 9 51 32 AM](https://github.com/brianteeman/loginmodal/assets/1907276/7be621a3-489f-4a6b-acf0-2c2228cd8504)

I also try to add the class directly to the <i> Awesome icon selector.... Same no ahref?

**Comment by Chacapamac** [comment]
@brianteeman , if you look at my last post, I cannot find the way for the surrounding span class “brianlogin” or the Awesome font to become a real link? — **I’m doing something wrong**

![Screen Shot 2024-04-07 at 10 45 51 PM](https://github.com/brianteeman/loginmodal/assets/1907276/333133d9-a049-443c-b989-036eb514467f)

**Comment by Chacapamac** [comment]
**Forget all that I find a trick** 😀

**I use this code:**
`<div class="logindiv"><a href="#" class="brianlogin"> <span class="awesome"><i class="fas fa-user fa-fw fa-login"></i></span></a>`
