### ISSUE TITLE
Password form-group Button alignment

### ISSUE THREAD

**Issue by ghost** [brianteeman/loginmodal#2]
Hi,

Thanks for the module. The most beautiful login module available in the Extensions directory.

There's a little overlooked thing here (I don't know if this is what it should be.). Please see the image below.,

![modal](https://user-images.githubusercontent.com/423588/182578336-5a4ffa7c-ebd8-46a6-80c5-e95fa7dce4bb.jpg)

I added the code below to a new user.css file and the problem was solved.

`#loginModal .btn {
    margin-right: 0;
}`

Result

![modal-2](https://user-images.githubusercontent.com/423588/182579870-7de94d33-eae0-4332-be0f-1d3dd286a4b4.jpg)

* J! 4.2.0-rc2-dev
* PHP 8.1.x

Thanks again, regards

**Comment by brianteeman** [comment]
Thank you for taking the time to test and report your findings. 

I have a custom layout for my login module o I didnt see this.

It is caused by 
`.modal .btn {
    margin-right: 0.5rem;
}`

**Comment by mariantanase** [comment]
I also added on my user.css, this code to unify the background:
```
.input-password-toggle {
  background-color: #eaedf0;
}
```
