### ISSUE TITLE
Noob question but, what am I doing wrong?

### ISSUE THREAD

**Issue by OddMoll** [brianteeman/loginmodal#3]
![image](https://user-images.githubusercontent.com/112466408/187368611-0b0c8d98-f7da-443a-89e5-5d733f959c7f.png)

I installed the files, created a log in module and published it to "modal" (which wasn't a default option so I just typed it myself, I don't know if that's alright). But I still see no log in option when I load the website. Did I miss a step?

Thank you for your time.

**Comment by brianteeman** [comment]
All correct so far.

The module needs to be triggered to popup by a selector in your content. This is configured in the plugin. For example if you create a menu item for login and then click on that instead of the page loading the login form a popup opens instead

**Comment by OddMoll** [comment]
Sorry for the late response, I'll be swamped with work so I'll need a bit of time to try this out! I appreciate your quick help!

**Comment by graebeerd** [comment]
After what you did above ---

Create a menu item named Login/Register, set it to System Link then URL type.
Set URL field to #login
Set Access as Guest
Save and Close

Create another menu item named Logout, set it to System Link then URL type.
Set URL to #login
Set Access to Registered (if that's how you have your site set for registration)
Save and Close.

Works fine and I wanted to give Tim an atta boy on the JED but it appears to be under attack at the moment or simply rekt

**Comment by OddMoll** [comment]
Thank you so much everyone!!! I'll test it asap and let you know how it went :D

**Comment by OddMoll** [comment]
I seem to be missing something, because while the "Login" button does appear on the menu of the website now, clicking it doesn't do anything :( 
![image](https://user-images.githubusercontent.com/112466408/188040590-7657d46b-8668-4874-96e4-dc160d6f0699.png)

**Comment by graebeerd** [comment]
Is the plugin enabled and is the login module set for 'all pages' ?

**Comment by OddMoll** [comment]
Thank you again for helping out a noob TvT

Out at work again but Imma get back to you asap! Figured sending screenshots to answer this would help in case I misunderstand something

**Comment by OddMoll** [comment]
Late update, but
the plug in seems enabled:
![image](https://user-images.githubusercontent.com/112466408/188292896-45991073-a26f-4137-830a-dc9520db25dc.png)

and the module's set at all pages:
![image](https://user-images.githubusercontent.com/112466408/188293200-371d39cc-fc07-439a-a93d-8814c4c7f0f6.png)

**Comment by graebeerd** [comment]
While it works in most instances, I have found that set as a menu item it doesn't work on a Kunena or Ignite Gallery menu item.
Possibly because of their integration of the Joomla login. This might be overcome by reordering it in the plugins to be above either of those but I haven't tried it.

**Comment by brianteeman** [comment]
you will just need to inspect their links to find the correct css attributes that they use to identify a login and then add that to the plugin params

**Comment by Bordspelwereld** [comment]
Thank you so far!

Everything works.

But I can't get the menu to act like I expect it to do.

A. When I set the LOGIN menu item to "guest" it doesn't show. It does when I set it to "public".
B. After I have logged in the LOGOUT menu item shows... but also the LOGIN menu item. I does not disappear. I have two menu items then.

What is it that I do wrong?
have I missed a step?

**Comment by brianteeman** [comment]
Make sure that the guest user group is set correctly

![image](https://user-images.githubusercontent.com/1296369/221547654-fcbe26da-23cc-41e8-af59-157708768c51.png)

**Comment by Bordspelwereld** [comment]
One of the fastest replies ever!

Everything works perfectly now.

T H A N K S !

BTW: I saw the scalahosting ad on joomla.org... did you gained some weight?

greetz

**Comment by brianteeman** [comment]
yes - side effect iof lockdown and getting old
