### ISSUE TITLE
Great Plugin ... but

### ISSUE THREAD

**Issue by barryRPal** [brianteeman/loginmodal#6]
Installed & worked straight away !
Menu Item -> Log In SUPER
But, I have menu item only for Registered User for Log Out. This did work before plugin but now does nothing - never did show anything, just quietly logged out.
Tried new logout menu item  URL -> #login but still click on this does nothing ????

**Comment by brianteeman** [comment]
in the plugin settings make sure that you only have a[href*="login"] set as the selector. That will prevent the plugin taking over the logout link and it will silently log you out as before

**Comment by barryRPal** [comment]
Excellent !!
Thank you for a great plugin.
