### ISSUE TITLE
Position "Modal"

### ISSUE THREAD

**Issue by kosh2323** [brianteeman/loginmodal#7]
Hi Brian. At first thanks for the plugin, it works great. Are there any further updates and support planned? And I have an academic interest, you have written that after enabling the plugin, the "Login" module itself should be displayed in the "Modal" position. Where does this position come from, it is virtual if it is not in the file TemplateDetails.xml ? I searched in the official documentation about this method, but could not find anything. Please explain.

**Comment by brianteeman** [comment]
>  Are there any further updates and support planned? 

No

> Where does this position come from, it is virtual if it is not in the file TemplateDetails.xml ?

it is virtual

**Comment by kosh2323** [comment]
It's a pity that there is no support, the plugin has stopped working....
