### ISSUE TITLE
Works well on all pages EXCEPT

### ISSUE THREAD

**Issue by barryRayPal** [brianteeman/loginmodal#8]
The attempted link is

https://baup.org.uk/events-calendar#login

AND

https://baup.org.uk/events-calendar/course/in-person-course/advanced-bladder-pathology-course-leeds-crs039#login

all others work fine like

https://baup.org.uk/contact-us#login

**Comment by brianteeman** [comment]
I can tell from the browser console that its caused by a javascript error. 

It appears to be conflicting with the javascript in the calendar that is used to open a booking form.
